version: '3.8'

services:

  my_app:
    build:
      context: .
      dockerfile: TP2_2.dockerfile
    deploy:
      replicas: 4
    restart: always
    environment:
      - PING_LISTEN_PORT=3000
    networks:
      - front-network

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - my_app
    networks:
      - front-network

networks:
  front-network:
